AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disable overly strict metrics - code works and is readable
Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

# Allow has_* predicate names (Ruby convention varies)
Naming/PredicateName:
  Enabled: false

# eval is intentionally used for syntax validation
Security/Eval:
  Exclude:
    - "lib/isort/syntax_validator.rb"

# Allow top-level mixin usage in test fixtures
Style/MixinUsage:
  Exclude:
    - "spec/fixtures/**/*"

# Allow script files without execute permission
Lint/ScriptPermission:
  Enabled: false

# Duplicate branches are intentional in some cases (consistent error handling)
Lint/DuplicateBranch:
  Enabled: false

# Allow unused variables from multiple assignment (Open3.capture3)
Lint/UselessAssignment:
  Exclude:
    - "test_local.rb"

# Gemspec supports 2.6+ but RuboCop targets 3.0 for linting - this is intentional
Gemspec/RequiredRubyVersion:
  Enabled: false

# eval is used for syntax checking - no interpolation doc needed
Style/DocumentDynamicEvalDefinition:
  Enabled: false

# Allow explicit min/max instead of clamp for clarity
Style/ComparableClamp:
  Enabled: false
